### ISSUE TITLE
fuelgas bioethanolgas went missing

### ISSUE THREAD

**Issue by TheMrCaveman** [BCA-Team/Buildcraft-Additions#392]
fuel and bioethanol went missing after upgrading from 2.1.1 to 2.1.2
http://i.imgur.com/2GnYW3U.png

refinery is also not taking oil anymore?

**Comment by AEnterprise** [comment]
hmm, did you update your forge?

**Comment by TheMrCaveman** [comment]
yes tried everything from 1370 en up

**Comment by AEnterprise** [comment]
take a backup and ignore, probably caused by the forge fluid changes

**Comment by AEnterprise** [comment]
@TheMrCaveman : is this fixed now?

**Comment by TheMrCaveman** [comment]
No it is still missing when upgrading. So refinery is not working anymore. 
It's not taking oil anymore. And all the fuel and bioethanol is simply not there anymore.
Only if i use forge 1343 or below the issue is not happening.

**Comment by iTitus** [comment]
Maybe the fluid registration happens "too late" for Forge?

**Comment by iTitus** [comment]
Any warnings about that in the console?

**Comment by AEnterprise** [comment]
works fine on my end, check the configs to make sure the multiblock refinery is enabled

**Comment by TheMrCaveman** [comment]
http://pastebin.com/kzmBvPiQ my server boot console and yes that is enabled!

Still not working here

**Comment by iTitus** [comment]
I see some warnings about BCA trying to register null-fluids.
We have added a null-check to the registration, not much we can do else.
I blame Cauldron :P

**Comment by TheMrCaveman** [comment]
Well here is a forge only boot:  http://pastebin.com/EQVLvr9x

And this is after confirming:  http://pastebin.com/9sb08vSN

Still not working

**Comment by iTitus** [comment]
Maybe BCA 2.1.3 will fix this. But this version is only compatible with BC7
